name: build

on:
 push:
   paths: ServerLaunchTrigger/self-hosted/*
 # schedule:
 #   - cron: '0 16/6 * * *'
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#scheduled-events





permissions:
  contents: write

jobs:
  # SHLinuxamd64: 
  #   name: Self-hosted Linux amd64
  #   runs-on: shmuid.1_ubuntu.x64_VMMTSL
  #   # timeout-minutes: 10
  #   continue-on-error: true
  #
  #   steps:
  #   - uses: actions/checkout@v4
  #   - run: sudo chmod 777 shopt.amd64.FastBuild.sh MTcompileSleep.sh
  #   - run: ${{github.workspace}}/MTcompileSleep.sh &
  #   - name: Download archive
  #     uses: dsaltares/fetch-gh-release-asset@1.1.1
  #     with: 
  #       file: server.zip
  #       target: 'archive.zip'
  #   - name: Download openp2p config
  #     uses: dsaltares/fetch-gh-release-asset@1.1.1
  #     with:
  #       file: openp2p.config.json
  #       target: 'openp2p.config.json'
  #   - run: sudo bash -c ${{github.workspace}}/shopt.amd64.FastBuild.sh

  #   - name: upload config.json to release
  #     uses: svenstaro/upload-release-action@v2
  #     with: 
  #       file: ${{github.workspace}}/WKSPC/packwork/config.json
  #       asset_name: openp2p.config.json
  #       tag: "archive"
  #       overwrite: true
  #   - name: upload server.zip to release
  #     uses: svenstaro/upload-release-action@v2
  #     with:
  #       file: ${{github.workspace}}/WKSPC/packwork/server.zip
  #       asset_name: server.zip
  #       tag: "archive"
  #       overwrite: true

  #   - name: Backup game archive
  #     uses: actions/upload-artifact@v4
  #     with: 
  #       compression-level: 9
  #       if-no-files-found: warn
  #       name: backup
  #       path: ${{github.workspace}}/WKSPC/packwork/server.zip
  #   - name: Upload logs to artifacts
  #     uses: actions/upload-artifact@v4
  #     with: 
  #       compression-level: 9
  #       if-no-files-found: warn
  #       name: logs
  #       path: |
  #         ${{github.workspace}}/openp2p.log
  #         ${{github.workspace}}/TCPLE.log
  #         ${{github.workspace}}/Ttimer.log


  # SHLinuxarm64:
  #   name: Self-hosted Linux arm64
  #   runs-on: shmuid.2_ubuntu.arm64_CTMTSL
  #   # timeout-minutes: 10
  #   continue-on-error: true
  #   steps:
  #   - uses: actions/checkout@v4
  #   - run: sudo chmod 777 shopt.arm64.FastBuild.sh MTcompileSleep.sh
  #   - run: ${{github.workspace}}/MTcompileSleep.sh &
  #   - name: Download archive
  #     uses: dsaltares/fetch-gh-release-asset@1.1.1
  #     with: 
  #       file: server.zip
  #       target: 'archive.zip'
  #   - name: Download openp2p config
  #     uses: dsaltares/fetch-gh-release-asset@1.1.1
  #     with:
  #       file: openp2p.config.json
  #       target: 'openp2p.config.json'
  #   - run: sudo bash -c ${{github.workspace}}/shopt.arm64.FastBuild.sh

  #   - name: upload config.json to release
  #     uses: svenstaro/upload-release-action@v2
  #     with: 
  #       file: ${{github.workspace}}/WKSPC/packwork/config.json
  #       asset_name: openp2p.config.json
  #       tag: "archive"
  #       overwrite: true
  #   - name: upload server.zip to release
  #     uses: svenstaro/upload-release-action@v2
  #     with:
  #       file: ${{github.workspace}}/WKSPC/packwork/server.zip
  #       asset_name: server.zip
  #       tag: "archive"
  #       overwrite: true

  #   - name: Backup game archive
  #     uses: actions/upload-artifact@v4
  #     with: 
  #       compression-level: 9
  #       if-no-files-found: warn
  #       name: backup
  #       path: ${{github.workspace}}/WKSPC/packwork/server.zip
  #   - name: Upload logs to artifacts
  #     uses: actions/upload-artifact@v4
  #     with: 
  #       compression-level: 9
  #       if-no-files-found: warn
  #       name: logs
  #       path: |
  #         ${{github.workspace}}/openp2p.log
  #         ${{github.workspace}}/TCPLE.log
  #         ${{github.workspace}}/Ttimer.log



  SHWindowsx64:
    name: Self-hosted Windows amd64
    runs-on: shmuid.3_win.x64_PMMTSL
    # timeout-minutes: 100
    continue-on-error: true

    steps:
    - uses: actions/checkout@v4
    
    - run: ${{github.workspace}}\MTcompileSleep.bat
    - name: Download archive
      uses: dsaltares/fetch-gh-release-asset@1.1.1
      with: 
        file: server.zip
        target: 'archive.zip'
    - name: Download openp2p config
      uses: dsaltares/fetch-gh-release-asset@1.1.1
      with:
        file: openp2p.config.json
        target: 'openp2p.config.json'

    # - name: Restore token
    #   run: ${{github.workspace}}\WriteSecret.exe ${{secrets.P2PTOKEN}} openp2p.config.json 

    - run: ${{github.workspace}}\FastBuild.bat ${{secrets.P2PTOKEN}}

    # - name: Remove token
    #   run: |
    #     ${{github.workspace}}\WriteSecret.exe 00000000000000000000 ${{github.workspace}}\WKSPC\packwork\config.json
    #     ${{github.workspace}}\ReplaceSecret.exe ${{secrets.P2PTOKEN}} ${{github.workspace}}\openp2p.log 00000000000000000000 ${{github.workspace}}\Wopenp2p.log

    - name: upload config.json to release
      uses: svenstaro/upload-release-action@v2
      with: 
        file: ${{github.workspace}}\WKSPC\packwork\config.json
        asset_name: openp2p.config.json
        tag: "archive"
        overwrite: true
    - name: upload server.zip to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ${{github.workspace}}\WKSPC\packwork\server.zip
        asset_name: server.zip
        tag: "archive"
        overwrite: true
    - name: upload logs.gz to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ${{github.workspace}}\WKSPC\packwork\logs.gz
        asset_name: logs.gz
        tag: "archive"
        overwrite: true

    - name: Upload logs to artifacts
      uses: actions/upload-artifact@v4
      with: 
        compression-level: 0
        if-no-files-found: ignore
        name: publicWINDOWS.logs
        path: |
          ${{github.workspace}}\TCPLE.log
          ${{github.workspace}}\Ttimer.log
          ${{github.workspace}}\Wopenp2p.log

    - name: upload server.zip
      uses: actions/upload-artifact@v4
      with: 
        name: backup
        path: ${{github.workspace}}\WKSPC\packwork\server.zip
